### ISSUE TITLE
Redundant Monitors array in UserModel

### ISSUE THREAD

**Issue by shawnmuzick** [Champion-Devs/ZappNode#32]
The monitors array in the userModel is redundant, as the monitorModel contains references to the user.

**Comment by zeyad-kay** [comment]
I think we should keep it and remove the user references from the monitors as it could decrease the reading time of the data as the number of users and monitors increases.

Also I think we should go with a single collection that contains the user with the array of monitors embedded in the user model without separately creating a new monitors collection. this way we can only access the data from a single location

**Comment by shawnmuzick** [comment]
change to structure makes this not an issue, so I'm marking it closed
